### ISSUE TITLE
System Dashboard | Authors

### ISSUE THREAD

**Issue by hpyhacking** [knewplay/knewhub#15]
# Authors

## Index View

- Could be searched by keyword to match the name
- Not create new one

### Table

- ID
- Name (author name)
- Created (created time lag)
- View (show the view as reader in a new tab)
- Edit (edit view)

## Edit View

- ID (readonly)
- Name (readonly)

**Comment by jp524** [comment]
1. I don't think it's possible to have the name be read-only on the 'edit view'. Should this view simply be removed then?
2. On the index view, should the link to `Destroy` be removed?
3. The notes don't mention the 'show view'. Is the 'show view' below acceptable?

![Image](https://github.com/knewplay/knewhub/assets/85654561/9df98660-ba73-4bba-bbbf-e887c186d9c4)
![Image](https://github.com/knewplay/knewhub/assets/85654561/d8ac6b5a-32a3-43cc-9506-c43c0ef557cc)
![Image](https://github.com/knewplay/knewhub/assets/85654561/0535db9f-e78f-4991-a4db-f8c2b63ccb9d)

**Comment by hpyhacking** [comment]
> * I don't think it's possible to have the name be read-only on the 'edit view'. Should this view simply be removed then?
> * On the index view, should the link to `Destroy` be removed?
> * The notes don't mention the 'show view'. Is the 'show view' below acceptable?

1. Could add a read-only field to edit view? If yes, add 'name' to the edit view.
2. No 'destroy' link and controller's action, only show things on the Table list in Index View.
3. No show view, if could show read-only field in edit view.

**Comment by hpyhacking** [comment]
I think the name for author is a new requirement on the #18
